site_name: AOE Wiki
site_url: https://teamaof.github.io/AOE-Wiki/
theme:
  name: material
  logo: img/EOA_logoB.png
  favicon: img/eoa_fav.ico
  
  font:
    text: Geist
  
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: red    
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: orange      
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
        
markdown_extensions:
  - admonition
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: TeamAOF/AOE-Wiki
      branch: wiki      

copyright: Copyright &copy; 2025 Team AOE

nav:
  - Home: index.md
  - Mod Packs:
    - Craftoria: modpacks/Craftoria.md
    - All of Fabric 7: modpacks/aof7.md
    - All of Fabric 6: modpacks/aof6.md
    - All of Fabric 5: modpacks/aof5.md
    - All of Fabric 4: modpacks/aof4.md
    - All of Fabric 3: modpacks/aof3.md
  - Servers:
    - Official Servers: servers/official_servers.md
    - Your own server: servers/server.md
  - Launchers:
    - CurseForge: launchers/curseforge.md
    - Prism Launcher: launchers/prism.md
  - How do I...?: howdoi/howdoi.md